apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-prod
 
spec:
  project: pacman
  source:
    repoURL: https://github.com/nkirui/pacman.git
    path: infra/helm/pacman
    targetRevision: HEAD
    helm:
      valueFiles:
        - prod.yaml
  destination:
    name: in-cluster
    namespace: prod
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true