apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-sbox
 
spec:
  project: pacman
  source:
    repoURL: https://github.com/Nkirui/action-pacman.git
    path: infra/helm/pacman
    targetRevision: HEAD
    helm:
      valueFiles:
        - sbox.yaml
  destination:
    name: in-cluster
    namespace: sbox
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true