apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: gopacman
  labels:
    app: {{ .Chart.Name }}
 
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      {{- if .Values.deployment.force }}
      annotations:
        roller: {{ .Files.Get "crds/vcs/hash" | trim }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default (.Files.Get "crds/vcs/tag" | trim) }}"
          imagePullPolicy: {{ .Values.image.pull }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}