env:
  HTTP_ADDR: :8080
 
image:
  name: you/pacman
  tag: latest
  pull: Always
 
deployment:
  force: true
  replicas: 1
  container:
    name: go
    port: 8080
 
service:
  type: ClusterIP
  port: 8080