env:
  HTTP_ADDR: :8080
  NAMESPACE: prod 
 
image:
  name: nkirui2030/pacman
  tag: ""
  pull: IfNotPresent
 
deployment:
  force: false
  replicas: 3
  container:
    name: go
    port: 8080
 
service:
  type: ClusterIP
  port: 8080