env:
  HTTP_ADDR: :8080
  NAMESPACE: sbox
 
image:
  name: nkirui2030/pacman
  tag: v1.1.0-beta
  pull: Never
 
deployment:
  force: false
  replicas: 2
  container:
    name: go
    port: 8080
 
service:
  type: ClusterIP
  port: 8080